version: '3'
services:
  database:
    build: database
    networks:
      default:
        ipv4_address: 172.16.5.10
    restart: always
    command: --default-authentication-plugin=mysql_native_password --sql_mode=""
    environment:
        - MYSQL_DATABASE=db
        - MYSQL_USER=euterpi
        - MYSQL_ROOT_PASSWORD=?2A_1fdrqWbVQc1hTRzhk+4ckI
        - MYSQL_PASSWORD=?2A_1fdrqWbVQc1hTRzhk+4ckI
  webserver:
    build: webserver
    ports:
      - "7500:80"
    networks:
      default:
        ipv4_address: 172.16.5.11
    restart: always
networks:
  default:
    external:
      name: sql-truncation
